### ISSUE TITLE
trouble shooting `woman` generations?

### ISSUE THREAD

**Issue by dcsan** [laurenceday/Dreambooth-Ion-Cannon#1]
hey thanks for this! I've fine-tuned a model on the `man` class and things worked fine. but I am trying a `woman` and the raw images and samples come out identical no matter what I do.

are there any other steps to trouble shoot this? I can confirm the files are named as:

```
root@C.5408015:/workspace/Dreambooth-Ion-Cannon$ tree training_samples/

training_samples/
└── woman
    ├── emma woman_001.png
    ├── emma woman_002.png
    ├── emma woman_003.png
    ├── emma woman_004.png
    ├── emma woman_005.png
    ├── emma woman_006.png
    ├── emma woman_007.png
```

and the notebook vars are initialized as:

```
target_name = "emma"
target_class = "woman"
```

not sure how else I could mess it up :)
any other hints where to look? I created a clean new vast instance and have done this twice now with identical results.

the raw gallery image comes out as the attached, both times (even though I'm using more training images now)

any other suggestions appreciated!

![emma_raw-0000](https://user-images.githubusercontent.com/514002/197942399-199c2f36-dadc-4541-bf0f-ff3f46bcb07f.jpg)

**Comment by dcsan** [comment]
I can confirm I get absolutely identical images on a second run on a clean new instance. so it seems somehow the training class is being ignored. the `target_name` "emma" is in the file names tho:

`emma_blackwhite_0.png`

![emma_blackwhite_0](https://user-images.githubusercontent.com/514002/197943232-8c70525d-9dea-4006-a372-abbd5aa32db2.png)

**Comment by dcsan** [comment]
Oh it's a GPU out of mem error.
also noticed i uploaded a `.DS_Store` mac file by accident...

I wonder if you have guidelines on how many images could be uploaded generally?
eg how many / big files?
seems to be a problem for the Tesla instances, even the a 10x Tesla seems capped at 16GB of VRAM:

![image](https://user-images.githubusercontent.com/514002/197947072-c2879373-7b42-4ff8-937c-b889fbb7e87a.png)


> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.49 GiB already allocated; 15.69 MiB free; 14.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by twro2022** [comment]
Must have 24GB - "One critical choice you need to make is that whatever you rent must have 24 GB VRAM"

**Comment by dcsan** [comment]
got it thanks! i overlooked that in the README. might be worth having some code to do a startup check at the beginning and fatal if there's for sure not enough vram.
